//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""f02c2c28-ebea-4690-91cb-dd4e5fdd1e8b"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e70e2112-a56e-4631-8d7c-9d014ee64672"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0c739e78-0117-4cbf-aa8d-8c14a052d029"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""cc1bf0fa-fa82-4166-bf0b-3c8ca0e18987"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""cedcc86c-1f2b-4e46-a72f-dd3e31e0a789"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Thrust"",
                    ""type"": ""Button"",
                    ""id"": ""376de3b7-30b0-412a-96ff-266458ebac84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Primary Fire"",
                    ""type"": ""Button"",
                    ""id"": ""45124d59-512a-45ea-b067-de8c9fc23631"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Secondary Fire"",
                    ""type"": ""Button"",
                    ""id"": ""87db35d2-8c2a-44f2-912a-b93a959fdac7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select Weapon 1"",
                    ""type"": ""Button"",
                    ""id"": ""f23f8c2a-5fe6-46bd-811f-ca16561b05c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Weapon 2"",
                    ""type"": ""Button"",
                    ""id"": ""43c97492-1fc0-41e7-a226-e8dcc2391691"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Weapon 3"",
                    ""type"": ""Button"",
                    ""id"": ""b5f1e94b-22df-4cf7-8795-93d0fafe8f8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Weapon 4"",
                    ""type"": ""Button"",
                    ""id"": ""8daa6407-4ec4-4009-b3b9-45a1cd5ada76"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Weapon 5"",
                    ""type"": ""Button"",
                    ""id"": ""23366272-8210-439a-945a-8ebe41126e7c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Weapon 6"",
                    ""type"": ""Button"",
                    ""id"": ""9f6b532c-6036-460f-bc7d-6cf4ba7cd213"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Weapon 7"",
                    ""type"": ""Button"",
                    ""id"": ""a8c7769c-5a63-44c4-be43-c860095a4ba4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Weapon 8"",
                    ""type"": ""Button"",
                    ""id"": ""7a1b2719-4991-4aec-96e6-b4d3696765d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Weapon 9"",
                    ""type"": ""Button"",
                    ""id"": ""bca50deb-4486-4e54-8cfe-6055c07108dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select Weapon 10"",
                    ""type"": ""Button"",
                    ""id"": ""c893f06a-2c09-4489-b8a5-d5112fbd4e04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD-like"",
                    ""id"": ""bc29283e-5647-476c-9f95-5f8fece690d9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d8035808-1400-49ae-b07c-6b82b7ada058"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bd0dfd1c-80e7-4686-be11-e3d3192a4dca"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2b15507f-c4b1-492c-9db6-068c9ec8f4ff"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f9c2c3c9-6522-4577-b608-a1b2d28abfb8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""157688ff-0dee-4d64-9d7f-6ec43337e4e7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b1d2e83-4914-4c50-8087-f2d948df1b9c"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18fc62b1-efb7-4887-ab73-7f42bc57cd57"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6f2052f-be8f-42b9-84d4-52b35f90b20d"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae3ce9d7-a85b-4d69-a7aa-6f64234e056a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select Weapon 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc7b6728-a2a9-4a06-9541-cfd11f556286"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select Weapon 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""879ff8e7-a317-4afd-9827-b854c3ac053a"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select Weapon 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29d3efe6-d10f-4045-8df6-6d05023df7bb"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select Weapon 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f90261b3-986c-414c-be18-94addfd7411b"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select Weapon 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f112910f-1376-484f-8c9b-fee73d6eddf4"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select Weapon 6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf6283a8-92f2-4bbb-b04a-af848c2b29b0"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select Weapon 7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7538b6e6-eb97-41e2-a8cc-a33ed2463876"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select Weapon 8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e58ae91-bf76-4f69-8597-1567638678a0"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select Weapon 9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fec7351-0a48-4424-bdb9-0853cffb7c8f"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select Weapon 10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24974ef8-ce3b-4587-96a1-bba9f80f7b3c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Primary Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c555fde0-0404-40d7-9f34-b0b3e515028b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Secondary Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
        m_Player_Thrust = m_Player.FindAction("Thrust", throwIfNotFound: true);
        m_Player_PrimaryFire = m_Player.FindAction("Primary Fire", throwIfNotFound: true);
        m_Player_SecondaryFire = m_Player.FindAction("Secondary Fire", throwIfNotFound: true);
        m_Player_SelectWeapon1 = m_Player.FindAction("Select Weapon 1", throwIfNotFound: true);
        m_Player_SelectWeapon2 = m_Player.FindAction("Select Weapon 2", throwIfNotFound: true);
        m_Player_SelectWeapon3 = m_Player.FindAction("Select Weapon 3", throwIfNotFound: true);
        m_Player_SelectWeapon4 = m_Player.FindAction("Select Weapon 4", throwIfNotFound: true);
        m_Player_SelectWeapon5 = m_Player.FindAction("Select Weapon 5", throwIfNotFound: true);
        m_Player_SelectWeapon6 = m_Player.FindAction("Select Weapon 6", throwIfNotFound: true);
        m_Player_SelectWeapon7 = m_Player.FindAction("Select Weapon 7", throwIfNotFound: true);
        m_Player_SelectWeapon8 = m_Player.FindAction("Select Weapon 8", throwIfNotFound: true);
        m_Player_SelectWeapon9 = m_Player.FindAction("Select Weapon 9", throwIfNotFound: true);
        m_Player_SelectWeapon10 = m_Player.FindAction("Select Weapon 10", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Crouch;
    private readonly InputAction m_Player_Thrust;
    private readonly InputAction m_Player_PrimaryFire;
    private readonly InputAction m_Player_SecondaryFire;
    private readonly InputAction m_Player_SelectWeapon1;
    private readonly InputAction m_Player_SelectWeapon2;
    private readonly InputAction m_Player_SelectWeapon3;
    private readonly InputAction m_Player_SelectWeapon4;
    private readonly InputAction m_Player_SelectWeapon5;
    private readonly InputAction m_Player_SelectWeapon6;
    private readonly InputAction m_Player_SelectWeapon7;
    private readonly InputAction m_Player_SelectWeapon8;
    private readonly InputAction m_Player_SelectWeapon9;
    private readonly InputAction m_Player_SelectWeapon10;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputAction @Thrust => m_Wrapper.m_Player_Thrust;
        public InputAction @PrimaryFire => m_Wrapper.m_Player_PrimaryFire;
        public InputAction @SecondaryFire => m_Wrapper.m_Player_SecondaryFire;
        public InputAction @SelectWeapon1 => m_Wrapper.m_Player_SelectWeapon1;
        public InputAction @SelectWeapon2 => m_Wrapper.m_Player_SelectWeapon2;
        public InputAction @SelectWeapon3 => m_Wrapper.m_Player_SelectWeapon3;
        public InputAction @SelectWeapon4 => m_Wrapper.m_Player_SelectWeapon4;
        public InputAction @SelectWeapon5 => m_Wrapper.m_Player_SelectWeapon5;
        public InputAction @SelectWeapon6 => m_Wrapper.m_Player_SelectWeapon6;
        public InputAction @SelectWeapon7 => m_Wrapper.m_Player_SelectWeapon7;
        public InputAction @SelectWeapon8 => m_Wrapper.m_Player_SelectWeapon8;
        public InputAction @SelectWeapon9 => m_Wrapper.m_Player_SelectWeapon9;
        public InputAction @SelectWeapon10 => m_Wrapper.m_Player_SelectWeapon10;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Crouch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Thrust.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThrust;
                @Thrust.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThrust;
                @Thrust.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThrust;
                @PrimaryFire.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPrimaryFire;
                @PrimaryFire.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPrimaryFire;
                @PrimaryFire.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPrimaryFire;
                @SecondaryFire.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondaryFire;
                @SecondaryFire.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondaryFire;
                @SecondaryFire.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondaryFire;
                @SelectWeapon1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon1;
                @SelectWeapon1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon1;
                @SelectWeapon1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon1;
                @SelectWeapon2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon2;
                @SelectWeapon2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon2;
                @SelectWeapon2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon2;
                @SelectWeapon3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon3;
                @SelectWeapon3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon3;
                @SelectWeapon3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon3;
                @SelectWeapon4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon4;
                @SelectWeapon4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon4;
                @SelectWeapon4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon4;
                @SelectWeapon5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon5;
                @SelectWeapon5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon5;
                @SelectWeapon5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon5;
                @SelectWeapon6.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon6;
                @SelectWeapon6.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon6;
                @SelectWeapon6.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon6;
                @SelectWeapon7.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon7;
                @SelectWeapon7.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon7;
                @SelectWeapon7.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon7;
                @SelectWeapon8.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon8;
                @SelectWeapon8.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon8;
                @SelectWeapon8.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon8;
                @SelectWeapon9.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon9;
                @SelectWeapon9.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon9;
                @SelectWeapon9.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon9;
                @SelectWeapon10.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon10;
                @SelectWeapon10.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon10;
                @SelectWeapon10.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectWeapon10;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Thrust.started += instance.OnThrust;
                @Thrust.performed += instance.OnThrust;
                @Thrust.canceled += instance.OnThrust;
                @PrimaryFire.started += instance.OnPrimaryFire;
                @PrimaryFire.performed += instance.OnPrimaryFire;
                @PrimaryFire.canceled += instance.OnPrimaryFire;
                @SecondaryFire.started += instance.OnSecondaryFire;
                @SecondaryFire.performed += instance.OnSecondaryFire;
                @SecondaryFire.canceled += instance.OnSecondaryFire;
                @SelectWeapon1.started += instance.OnSelectWeapon1;
                @SelectWeapon1.performed += instance.OnSelectWeapon1;
                @SelectWeapon1.canceled += instance.OnSelectWeapon1;
                @SelectWeapon2.started += instance.OnSelectWeapon2;
                @SelectWeapon2.performed += instance.OnSelectWeapon2;
                @SelectWeapon2.canceled += instance.OnSelectWeapon2;
                @SelectWeapon3.started += instance.OnSelectWeapon3;
                @SelectWeapon3.performed += instance.OnSelectWeapon3;
                @SelectWeapon3.canceled += instance.OnSelectWeapon3;
                @SelectWeapon4.started += instance.OnSelectWeapon4;
                @SelectWeapon4.performed += instance.OnSelectWeapon4;
                @SelectWeapon4.canceled += instance.OnSelectWeapon4;
                @SelectWeapon5.started += instance.OnSelectWeapon5;
                @SelectWeapon5.performed += instance.OnSelectWeapon5;
                @SelectWeapon5.canceled += instance.OnSelectWeapon5;
                @SelectWeapon6.started += instance.OnSelectWeapon6;
                @SelectWeapon6.performed += instance.OnSelectWeapon6;
                @SelectWeapon6.canceled += instance.OnSelectWeapon6;
                @SelectWeapon7.started += instance.OnSelectWeapon7;
                @SelectWeapon7.performed += instance.OnSelectWeapon7;
                @SelectWeapon7.canceled += instance.OnSelectWeapon7;
                @SelectWeapon8.started += instance.OnSelectWeapon8;
                @SelectWeapon8.performed += instance.OnSelectWeapon8;
                @SelectWeapon8.canceled += instance.OnSelectWeapon8;
                @SelectWeapon9.started += instance.OnSelectWeapon9;
                @SelectWeapon9.performed += instance.OnSelectWeapon9;
                @SelectWeapon9.canceled += instance.OnSelectWeapon9;
                @SelectWeapon10.started += instance.OnSelectWeapon10;
                @SelectWeapon10.performed += instance.OnSelectWeapon10;
                @SelectWeapon10.canceled += instance.OnSelectWeapon10;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnLook(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnThrust(InputAction.CallbackContext context);
        void OnPrimaryFire(InputAction.CallbackContext context);
        void OnSecondaryFire(InputAction.CallbackContext context);
        void OnSelectWeapon1(InputAction.CallbackContext context);
        void OnSelectWeapon2(InputAction.CallbackContext context);
        void OnSelectWeapon3(InputAction.CallbackContext context);
        void OnSelectWeapon4(InputAction.CallbackContext context);
        void OnSelectWeapon5(InputAction.CallbackContext context);
        void OnSelectWeapon6(InputAction.CallbackContext context);
        void OnSelectWeapon7(InputAction.CallbackContext context);
        void OnSelectWeapon8(InputAction.CallbackContext context);
        void OnSelectWeapon9(InputAction.CallbackContext context);
        void OnSelectWeapon10(InputAction.CallbackContext context);
    }
}
